/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LevelDb */

#ifndef _Included_LevelDb
#define _Included_LevelDb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LevelDb
 * Method:    open
 * Signature: (Ljava/lang/String;ZZZZJB)J
 */
JNIEXPORT jlong JNICALL Java_LevelDb_open
  (JNIEnv *, jobject, jstring, jboolean, jboolean, jboolean, jboolean, jlong, jbyte);

/*
 * Class:     LevelDb
 * Method:    put
 * Signature: (J[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_LevelDb_put
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     LevelDb
 * Method:    get
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_LevelDb_get
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     LevelDb
 * Method:    delete
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_LevelDb_delete
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     LevelDb
 * Method:    iteratorNew
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_LevelDb_iteratorNew
  (JNIEnv *, jobject, jlong);

/*
 * Class:     LevelDb
 * Method:    iteratorSeekToFirst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_LevelDb_iteratorSeekToFirst
  (JNIEnv *, jobject, jlong);

/*
 * Class:     LevelDb
 * Method:    iteratorSeekToLast
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_LevelDb_iteratorSeekToLast
  (JNIEnv *, jobject, jlong);

/*
 * Class:     LevelDb
 * Method:    iteratorSeek
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_LevelDb_iteratorSeek
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     LevelDb
 * Method:    iteratorValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_LevelDb_iteratorValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     LevelDb
 * Method:    iteratorNext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_LevelDb_iteratorNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     LevelDb
 * Method:    iteratorPrev
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_LevelDb_iteratorPrev
  (JNIEnv *, jobject, jlong);

/*
 * Class:     LevelDb
 * Method:    iteratorKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_LevelDb_iteratorKey
  (JNIEnv *, jobject, jlong);

/*
 * Class:     LevelDb
 * Method:    iteratorValue
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_LevelDb_iteratorValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     LevelDb
 * Method:    iteratorClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_LevelDb_iteratorClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     LevelDb
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_LevelDb_close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
