/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    open
 * Signature: (Ljava/lang/String;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_Main_open
  (JNIEnv *, jobject, jstring, jboolean, jboolean);

/*
 * Class:     Main
 * Method:    put
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_Main_put
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     Main
 * Method:    get
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Main_get
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     Main
 * Method:    delete
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_Main_delete
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     Main
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
